
create table if not exists public.global_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null,
  body text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.global_chat_messages enable row level security;

-- Policies
create policy "Anyone can read global chat messages"
  on public.global_chat_messages for select
  using (true);

create policy "Authenticated users can insert global chat messages"
  on public.global_chat_messages for insert
  with check (auth.uid() = user_id);

-- Realtime
alter publication supabase_realtime add table public.global_chat_messages;
